# INSTANTIATE

In [1]:
import sys
sys.path.insert(1, '/Users/fnurr/Documents/WORKPLACE/vlrgg Unofficial REST API - updated/api/')
from scrape import Vlr
vlr = Vlr()

In [2]:
import pandas as pd
import json

# RESULTS

In [3]:
data = []
pages = list(range(1,227)) # pages 227 onwards are broken for scraping
for page in pages:
    data.append(vlr.vlr_score(page = page))
len(data)

226

In [4]:
results = pd.json_normalize(data[0]['data']['segments'])
for x in range(1, len(data)):
    results = results.append(pd.json_normalize(data[x]['data']['segments']))
results.head()

,team1,team2,score1,score2,time_completed,round_info,tournament_name,match_page,tournament_icon
0,Thunderbolts Gaming,Eternal Fire,2,1,7h 36m ago,Playoffs-Quarterfinals,Open Fire Legacy,/60968/thunderbolts-gaming-vs-eternal-fire-ope...,https://owcdn.net/img/60faced0e30b5.png
1,Surreal Esports,Regnum Carya Esports,2,0,10h 6m ago,Playoffs-Quarterfinals,Open Fire Legacy,/60967/surreal-esports-vs-regnum-carya-esports...,https://owcdn.net/img/60faced0e30b5.png
2,Action PH,Fallen5,2,0,13h 6m ago,Playoffs-Lower Final,The Esports Club - Challenger Series 6,/56828/action-ph-vs-fallen5-the-esports-club-c...,https://owcdn.net/img/61b930626ebac.png
3,Regnum Carya Esports,Besiktas Esports,9,13,1d 5h ago,Group Stage-Group B,Open Fire Legacy,/60861/regnum-carya-esports-vs-besiktas-esport...,https://owcdn.net/img/60faced0e30b5.png
4,Surreal Esports,OtherSide,13,7,1d 6h ago,Group Stage-Group A,Open Fire Legacy,/60860/surreal-esports-vs-otherside-open-fire-...,https://owcdn.net/img/60faced0e30b5.png

In [5]:
results.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11300 entries, 0 to 49
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   team1            11300 non-null  object
 1   team2            11300 non-null  object
 2   score1           11300 non-null  object
 3   score2           11300 non-null  object
 4   time_completed   11300 non-null  object
 5   round_info       11300 non-null  object
 6   tournament_name  11300 non-null  object
 7   match_page       11300 non-null  object
 8   tournament_icon  11300 non-null  object
dtypes: object(9)
memory usage: 882.8+ KB

In [6]:
results.to_csv('results.csv')

# Stats

maps:
- all
- ascent 5
- bind 1
- breeze 8
- fracture 9
- haven 2
- icebox 6
- split 3

In [7]:
data = []
region = ['na', 'eu', 'ap', 'sa', 'oce', 'mn']
agent = ['astra','breach','brimstone','chamber','cypher',
         'jett','kayo','killjoy','omen','phoenix','raze',
         'reyna','sage','skye','sova','viper','yoru']
map_id = ['1','2','3','5','6','8','9']
for region in region:
    for map_id in map_id:
        for agent in agent:
            data.append(vlr.vlr_stats(region = region, map_id = map_id, agent = agent))
len(data)

31

In [8]:
stats = pd.json_normalize(data[0]['data']['segments'])
stats.head()

,player,org,rds,average_combat_score,kill_deaths,average_damage_per_round,kills_per_round,assists_per_round,first_kills_per_round,first_deaths_per_round,...,clutch_success_percentage,clutch (won/played),total_kills,total_deaths,total_assists,total_first_kills,total_first_deaths,map_id,agent,region
0,jawgemo,T1A,46,304.5,1.58,186.0,1.07,0.22,0.13,0.11,...,0.11,1/6,26,49,31,10,6,1,astra,na
1,PapaSmurf,TLP,17,295.0,1.20,169.6,1.06,0.24,0.00,0.12,...,0.12,0/1,18,18,15,4,0,1,astra,na
2,Ponder,,39,290.5,1.29,198.2,1.03,0.21,0.10,0.08,...,0.08,0/5,29,40,31,8,4,1,astra,na
3,Bobovo,,84,280.8,1.56,162.0,1.06,0.27,0.19,0.10,...,0.10,1/13,29,89,57,23,16,1,astra,na
4,contii,RESO,23,274.0,1.10,167.1,0.96,0.39,0.13,0.00,...,0.00,0/2,22,22,20,9,3,1,astra,na

In [9]:
stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315 entries, 0 to 314
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   player                     315 non-null    object
 1   org                        315 non-null    object
 2   rds                        315 non-null    object
 3   average_combat_score       315 non-null    object
 4   kill_deaths                315 non-null    object
 5   average_damage_per_round   315 non-null    object
 6   kills_per_round            315 non-null    object
 7   assists_per_round          315 non-null    object
 8   first_kills_per_round      315 non-null    object
 9   first_deaths_per_round     315 non-null    object
 10  headshot_percentage        315 non-null    object
 11  clutch_success_percentage  315 non-null    object
 12  clutch (won/played)        315 non-null    object
 13  total_kills                315 non-null    object
 14  total_deaths               315 non-null    object
 15  total_assists              315 non-null    object
 16  total_first_kills          315 non-null    object
 17  total_first_deaths         315 non-null    object
 18  map_id                     315 non-null    object
 19  agent                      315 non-null    object
 20  region                     315 non-null    object
dtypes: object(21)
memory usage: 51.8+ KB

In [10]:
stats.to_csv('stats.csv')