In [1]:
import pandas as pd

In [2]:
file = 'matches_england.csv'
df = pd.read_csv(file, sep=';')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   wk            380 non-null    int64
 1   day           380 non-null    object
 2   date          380 non-null    object
 3   time          380 non-null    object
 4   home          380 non-null    object
 5   xg_home       333 non-null    float64
 6   score         333 non-null    object
 7   xg_away       333 non-null    float64
 8   away          380 non-null    object
 9   attendance    330 non-null    float64
 10  venue         380 non-null    object
 11  referee       333 non-null    object
 12  match_report  380 non-null    object
 13  notes         0 non-null      float64
 14  match_link    380 non-null    object
dtypes: float64(4), int64(1), object(10)
memory usage: 44.7+ KB

In [4]:
df.head()

,wk,day,date,time,home,xg_home,score,xg_away,away,attendance,venue,referee,match_report,notes,match_link
0,1,Fri,2022-08-05,20:00,Crystal Palace,1.2,0-2,1.0,Arsenal,25286.0,Selhurst Park,Anthony Taylor,Match Report,NaN,/en/matches/e62f6e78/Crystal-Palace-Arsenal-Au...
1,1,Sat,2022-08-06,12:30,Fulham,1.2,2-2,1.2,Liverpool,22207.0,Craven Cottage,Andy Madley,Match Report,NaN,/en/matches/6713c1dc/Fulham-Liverpool-August-6...
2,1,Sat,2022-08-06,15:00,Tottenham,1.5,4-1,0.5,Southampton,61732.0,Tottenham Hotspur Stadium,Andre Marriner,Match Report,NaN,/en/matches/09d8a999/Tottenham-Hotspur-Southam...
3,1,Sat,2022-08-06,15:00,Newcastle Utd,1.7,2-0,0.3,Nott'ham Forest,52245.0,St James' Park,Simon Hooper,Match Report,NaN,/en/matches/1ac96eb4/Newcastle-United-Nottingh...
4,1,Sat,2022-08-06,15:00,Leeds United,0.8,2-1,1.3,Wolves,36347.0,Elland Road,Robert Jones,Match Report,NaN,/en/matches/82702941/Leeds-United-Wolverhampto...